name = "megan-ai-relay"
main = "worker.js"
compatibility_date = "2025-01-01"

[vars]
AI_ENDPOINT = "https://integrate.api.nvidia.com/v1"
AI_MODEL = "meta/llama-3.2-11b-vision-instruct"

[[secrets_store_secrets]]
binding = "AI_API_KEY"
store_id = "b405dcaf41e84fe59a7637ff0be11621"
secret_name = "nvidia-api-key"

[[secrets_store_secrets]]
binding = "TAVILY_API_KEY"
store_id = "b405dcaf41e84fe59a7637ff0be11621"
secret_name = "tavily-api-key"
